# **Clean up location data**

We make the distributor location data uniform and enforce schema for consitent use later.

In [9]:
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv("distributor_locations_priority_geocoded.csv", index_col=[0])

df

,#,Distributors,County,Category,Agrodealers Potential for Commercial Farms,Locations,Locations_cleaned,Longitude,Latitude,geometry
0,1,Plum Pharmacy Limited,Machakos,Category A,High,VG4W+76G A3 Matuu Kenya,VG4W+76G A3 Matuu Kenya,37.548118,-1.144339,POINT (37.5481177 -1.1443392)
1,2,Mwangaza,Mashuru,Category A,Medium,V4WH+FQP Selengei,"V4WH+FQP Selengei , Kenya",37.129453,-2.103788,POINT (37.1294531 -2.1037875)
2,3,CHEP CHEP FARMERS AGROVET,Nakuru,Category A,High,CM6P+98Q Olenguruone Kenya,CM6P+98Q Olenguruone Kenya,35.685859,-0.589037,POINT (35.6858594 -0.5890375)
3,4,DAMCHEM STORES-KIMANA,Kajiado,Category A,High,5GXP+RM Kimana Kenya,5GXP+RM Kimana Kenya,37.536687,-2.800438,POINT (37.5366875 -2.8004375)
4,6,Esther Naserian Karanja,Kajiado,Category A,High,XM3W+3R Laset,"XM3W+3R Laset , Kenya",37.697063,-3.047312,POINT (37.6970625 -3.0473125)
5,7,Greengrove Agricare Ltd,Bomet,Category A,High,789W+F9 Silibwet,"789W+F9 Silibwet , Kenya",35.345937,-0.731312,POINT (35.3459375 -0.7313124999999999)
6,8,Mulot Vet Services,Narok,Category A,High,3C7M+7H Ngorengore Kenya,3C7M+7H Ngorengore Kenya,35.433937,-0.936813,POINT (35.4339375 -0.9368124999999999)
7,9,MASHAMBANI FARM INPUTS,Uasin Gishu,Category A,High,CWCM+6X Nyamira Kenya,CWCM+6X Nyamira Kenya,34.934937,-0.579437,POINT (34.9349375 -0.5794374999999999)
8,10,Paves Vet Agro,Trans Nzoia,Category A,High,229C+XF6 Kitale,"229C+XF6 Kitale , Kenya",35.021141,1.019912,POINT (35.0211406 1.0199125)
9,11,Solai Agrovet- Rumuruti,Laikipia,Category A,High,7G5P+64 Rumuruti,"7G5P+64 Rumuruti , Kenya",36.535313,0.258062,POINT (36.5353125 0.2580625)

## **Rename columns**

In [11]:
col_names = df.columns.tolist()
new_col_names = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")
)

col_name_mapping = {
    k: v for k, v in zip(col_names, new_col_names)
    if k != "#"
}

col_name_mapping["#"] = "distributor_id"

df = df.rename(columns=col_name_mapping)
df["distributor_id"] = np.arange(1, len(df) + 1)

In [12]:
df["locations_cleaned"]

0        VG4W+76G A3 Matuu Kenya
1     V4WH+FQP Selengei  , Kenya
2    CM6P+98Q Olenguruone Kenya
3         5GXP+RM Kimana Kenya
4        XM3W+3R Laset   , Kenya
5     789W+F9 Silibwet   , Kenya
6     3C7M+7H Ngorengore Kenya
7        CWCM+6X Nyamira Kenya
8       229C+XF6 Kitale  , Kenya
9     7G5P+64 Rumuruti   , Kenya
Name: locations_cleaned, dtype: object

In [13]:
df["addresses"] = (
    df["locations_cleaned"]
    .str.replace(",", "", regex=False)
    .str.replace(r"\s+", " ", regex=True) # more than one whitespace
    .str.strip()
)

df = df.drop(["locations", "locations_cleaned"], axis=1)

In [14]:
df

,distributor_id,distributors,county,category,agrodealers_potential_for_commercial_farms,longitude,latitude,geometry,addresses
0,1,Plum Pharmacy Limited,Machakos,Category A,High,37.548118,-1.144339,POINT (37.5481177 -1.1443392),VG4W+76G A3 Matuu Kenya
1,2,Mwangaza,Mashuru,Category A,Medium,37.129453,-2.103788,POINT (37.1294531 -2.1037875),V4WH+FQP Selengei Kenya
2,3,CHEP CHEP FARMERS AGROVET,Nakuru,Category A,High,35.685859,-0.589037,POINT (35.6858594 -0.5890375),CM6P+98Q Olenguruone Kenya
3,4,DAMCHEM STORES-KIMANA,Kajiado,Category A,High,37.536687,-2.800438,POINT (37.5366875 -2.8004375),5GXP+RM Kimana Kenya
4,5,Esther Naserian Karanja,Kajiado,Category A,High,37.697063,-3.047312,POINT (37.6970625 -3.0473125),XM3W+3R Laset Kenya
5,6,Greengrove Agricare Ltd,Bomet,Category A,High,35.345937,-0.731312,POINT (35.3459375 -0.7313124999999999),789W+F9 Silibwet Kenya
6,7,Mulot Vet Services,Narok,Category A,High,35.433937,-0.936813,POINT (35.4339375 -0.9368124999999999),3C7M+7H Ngorengore Kenya
7,8,MASHAMBANI FARM INPUTS,Uasin Gishu,Category A,High,34.934937,-0.579437,POINT (34.9349375 -0.5794374999999999),CWCM+6X Nyamira Kenya
8,9,Paves Vet Agro,Trans Nzoia,Category A,High,35.021141,1.019912,POINT (35.0211406 1.0199125),229C+XF6 Kitale Kenya
9,10,Solai Agrovet- Rumuruti,Laikipia,Category A,High,36.535313,0.258062,POINT (36.5353125 0.2580625),7G5P+64 Rumuruti Kenya

In [15]:
#df.to_csv("priority_distributors.csv", index=False)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   distributor_id                              10 non-null     int64
 1   distributors                                10 non-null     object
 2   county                                      10 non-null     object
 3   category                                    10 non-null     object
 4   agrodealers_potential_for_commercial_farms  10 non-null     object
 5   longitude                                   10 non-null     float64
 6   latitude                                    10 non-null     float64
 7   geometry                                    10 non-null     object
 8   addresses                                   10 non-null     object
dtypes: float64(2), int64(1), object(6)
memory usage: 800.0+ bytes